// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5PnUKJZ9lbxaK1IpXMIY3DUIjEryu3xg',
    appId: '1:223387694994:web:601a40ce53d74b2ed9f34b',
    messagingSenderId: '223387694994',
    projectId: 'terratreasures-cda36',
    authDomain: 'terratreasures-cda36.firebaseapp.com',
    storageBucket: 'terratreasures-cda36.appspot.com',
    measurementId: 'G-0P32NHC3BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhr08kTRb__ShkhawLi_Z0NahgTmC5qI',
    appId: '1:223387694994:android:6c40b2363b577495d9f34b',
    messagingSenderId: '223387694994',
    projectId: 'terratreasures-cda36',
    storageBucket: 'terratreasures-cda36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp3a2bAqmVIwY_05gVH4rUZP1jAShRJ8k',
    appId: '1:223387694994:ios:06725ae892b101a6d9f34b',
    messagingSenderId: '223387694994',
    projectId: 'terratreasures-cda36',
    storageBucket: 'terratreasures-cda36.appspot.com',
    iosBundleId: 'com.example.terraTreasures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp3a2bAqmVIwY_05gVH4rUZP1jAShRJ8k',
    appId: '1:223387694994:ios:c3a4a6f5860f5089d9f34b',
    messagingSenderId: '223387694994',
    projectId: 'terratreasures-cda36',
    storageBucket: 'terratreasures-cda36.appspot.com',
    iosBundleId: 'com.example.terraTreasures.RunnerTests',
  );
}
